DB_Pharmacy/DB_Pharmacy/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DB_Pharmacy.Filters;
using DB_Pharmacy.Models;
using DB_Pharmacy.Manager;
using System.IO;

namespace DB_Pharmacy.Controllers
{

    [AuthorizedUser]
    [ExceptionFilter]
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Addemp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Addemp(Employeemodel Emp, HttpPostedFileBase ImageFile)                                                                                                                    
        {
            if (ModelState.IsValid)
            {
                if (ImageFile == null)
                {
                    TempData["message"] = "Please Upload Employee Image";
                    return View();
                }
                else
                {
                    string Filename = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                    string Extension = Path.GetExtension(ImageFile.FileName);
                    Filename = Filename + DateTime.Now.ToString("yymmssfff") + Extension;
                    Emp.Imagepath = "~/ProjectData/" + Filename;
                    Filename = Path.Combine(Server.MapPath("~/ProjectData/"), Filename);
                    ImageFile.SaveAs(Filename);

                    Employeemanager obj = new Employeemanager();
                    int check = obj.Addemp(Emp);
                    if (check > 0)
                    {
                        TempData["message"] = "Your EmployeeID: " + check;
                        return RedirectToAction("Viewemp");
                    }
                    else
                    {
                        TempData["message"] = "Enter Item to be Inserted";
                        return View();
                    }

                }


            }
            else
            {
                TempData["message"] = "Enter Valid Item";
                return View();
            }
        }


        public ActionResult Viewemp()
        {
            Employeemanager obj = new Employeemanager();
            List<Employeemodel> empinfo = obj.GetAllEmp();
            return View(empinfo);
        }

        public ActionResult Deleteemp(int EID)
        {
            Employeemanager obj = new Employeemanager();
            bool check = obj.removeemp(EID);
            if (check)
            {
                TempData["Message"] = "data deleted successfulyl";
            }
            else
            {
                TempData["Message"] = "data dosen't delete, something wrong";
            }
            return RedirectToAction("Viewemp");
        }

        [HttpGet]
        public ActionResult Updateemp(int EID)
        {
            

            Employeemanager obj = new Employeemanager();
            Employeemodel emp = obj.getemp(EID);
            
            return View(emp);
        }

        [HttpPost]
        public ActionResult Updateemp(Employeemodel Emp)
        {
            Employeemanager obj = new Employeemanager();
            bool check = obj.updateemp(Emp);
            if (check)
            {
                return RedirectToAction("Viewemp");
            }
            else
            {
                TempData["message"] = "Error Ocured Try again";
                return View(Emp);
            }
            
        }
    }
}

DB_Pharmacy/DB_Pharmacy/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DB_Pharmacy.Models;
using DB_Pharmacy.Manager;
using DB_Pharmacy.Filters;

namespace DB_Pharmacy.Controllers
{
    [AuthorizedUser]
    [ExceptionFilter]

    public class ItemController : Controller
    {
        // GET: Medicine
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Addmed()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Addmed(Itemmodel Item)
        {

            if (ModelState.IsValid)
            {
                Itemmanager obj = new Itemmanager();
                int check = obj.Addmed(Item);
                if (check > 0)
                {
                    TempData["message"] = "Data Inserted your ItemID: " + check;
                    return RedirectToAction("Stockmed");
                }
                else
                {
                    TempData["message"] = "Enter Item to be Inserted";
                    return View();
                }
            }
            else
            {
                TempData["message"] = "Enter Valid Item";
                return View();
            }
            
        }

        [HttpGet]
        public ActionResult updatemed(int ItemID)
        {
            Itemmanager obj = new Itemmanager();
            Itemmodel item = obj.Getitem(ItemID);
            return View(item);
        }

        [HttpPost]
        public ActionResult updatemed(Itemmodel item)
        {
            Itemmanager obj = new Itemmanager();
            bool check = obj.updateitem(item);
            if (check)
            {
                return RedirectToAction("Stockmed");
            }
            else
            {
                TempData["Message"] = "Some error";
                return View(item);
            }
            
        }
        public ActionResult deletemed(int ItemID)
        {
            Itemmanager obj = new Itemmanager();
            bool check = obj.deleteitem(ItemID);
            if (check)
            {
                TempData["Message"] = "data deleted successfulyl";
            }
            else
            {
                TempData["Message"] = "data dosen't delete, something wrong";
            }
            return RedirectToAction("Stockmed");
        }

        public ActionResult Stockmed()
        {
            Itemmanager obj = new Itemmanager();
            List<Itemmodel> Adminitem = obj.Getallitem();
            return View(Adminitem);
        }
    }
}

DB_Pharmacy/DB_Pharmacy/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DB_Pharmacy.Models;
using DB_Pharmacy.Manager;
using DB_Pharmacy.Filters;

namespace DB_Pharmacy.Controllers
{
    [AuthorizedUser]
    [ExceptionFilter]
    public class PatientController : Controller
    {
        // GET: Patient
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Addpatient()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Addpatient(PatientModel PAT)
        {
            if (ModelState.IsValid)
            {

                PatientManager obj = new PatientManager();
                int check = obj.Addpatient(PAT);
                if (check > 0)
                {
                    TempData["message"] = "Your PatientID: " + check;
                    return RedirectToAction("Viewpatient");
                }
                else
                {
                    TempData["message"] = "Enter Records of Patient";
                    return View();
                }

            }
            else
            {
                TempData["message"] = "Enter Valid Informarion";
                return View();
            }
        }

        public ActionResult Viewpatient()
        {
            PatientManager obj = new PatientManager();
            List<PatientModel> PatInfo = obj.GetallPatient();
            return View(PatInfo);
        }

        [HttpGet]
        public ActionResult Editpatient(int PID)
        {
            PatientManager obj = new PatientManager();
            PatientModel PAT = obj.GetPat(PID);
            return View(PAT);
        }


        [HttpPost]
        public ActionResult Editpatient(PatientModel PAT)
        {
            PatientManager obj = new PatientManager();
            bool check = obj.EditPat(PAT);
            if (check)
            {
                return RedirectToAction("Viewpatient");
            }
            else
            {
                TempData["message"] = "Error Ocured Try again";
                return View(PAT);
            }
        }
    }
}

DB_Pharmacy/DB_Pharmacy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <title>@ViewBag.Title</title>

    <!-- Favicons -->
    <link href="~/Content/img/favicon.png" rel="icon">
    <link href="~/Content/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!--external css-->
    <link href="~/Content/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/css/zabuto_calendar.css">
    <link rel="stylesheet" type="text/css" href="~/Content/lib/gritter/css/jquery.gritter.css" />
    <!-- Custom styles for this template -->
    <link href="~/Content/css/style.css" rel="stylesheet">
    <link href="~/Content/css/style-responsive.css" rel="stylesheet">
    <script src="~/Content/lib/chart-master/Chart.js"></script>
    <link href="~/Content/MyStyle.css" rel="stylesheet" />
    <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
    <link rel="stylesheet" href="~/Content/lib/file-uploader/css/jquery.fileupload.css">
    <link rel="stylesheet" href="~/Content/lib/file-uploader/css/jquery.fileupload-ui.css">
    <!-- =======================================================
      Template Name: Dashio
      Template URL: https://templatemag.com/dashio-bootstrap-admin-template/
      Author: TemplateMag.com
      License: https://templatemag.com/license/
    ======================================================= -->
</head>

<body>
    <section id="container">
        <!-- **********************************************************************************************************************************************************
            TOP BAR CONTENT & NOTIFICATIONS
            *********************************************************************************************************************************************************** -->
        <!--header start-->
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>
            <!--logo start-->
            <a href="@Url.Action("Index","Home")" class="logo"><b>Pharma<span>Tech</span></b></a>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
            </div>
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" href="@Url.Action("logout","Home")">Logout</a></li>
                </ul>
            </div>
        </header>
        <!--header end-->
        <!-- **********************************************************************************************************************************************************
            MAIN SIDEBAR MENU
            *********************************************************************************************************************************************************** -->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <p class="centered"><a href="@Url.Action("Myaccount","Home")"><img src="@Url.Content(Session["PersonImage"].ToString())" class="img-circle" width="80"></a></p>
                    <h5 class="centered">@Session["PersonName"]</h5>
                    <li class="mt">
                        <a class="active" href="@Url.Action("Index","Home")">
                            <i class="fa fa-dashboard"></i>
                            <span>Home</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class="fa fa-desktop"></i>
                            <span>Items</span>
                        </a>
                        <ul class="sub">
                            <li><a href="@Url.Action("Addmed","Item")">Add Item</a></li>
                            <li><a href="@Url.Action("Stockmed","Item")">Stock Item</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class="fa fa-cogs"></i>
                            <span>Employee</span>
                        </a>
                        <ul class="sub">
                            <li><a href="@Url.Action("Addemp","Employee")">Add Employee</a></li>
                            <li><a href="@Url.Action("Viewemp","Employee")">Company Employee</a></li>
                        </ul>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;">
                            <i class="fa fa-tasks"></i>
                            <span>Patient</span>
                        </a>
                        <ul class="sub">
                            <li><a href="@Url.Action("Addpatient","Patient")">Add Patient</a></li>
                            <li><a href="@Url.Action("Viewpatient","Patient")">View Patient</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-map-marker"></i>
                            <span>Google Maps </span>
                        </a>
                    </li>
                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!-- **********************************************************************************************************************************************************
            MAIN CONTENT
            *********************************************************************************************************************************************************** -->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                @RenderBody()
                <div class="row">
                    <div class="col-lg-9 main-chart">
                        <!--CUSTOM CHART START -->
                        <div class="border-head">

                        </div>

                        <!--custom chart end-->
                        <div class="row mt">
                            <!-- SERVER STATUS PANELS -->
                        </div>
                    </div>
                </div>
                <!-- /col-lg-9 END SECTION MIDDLE -->
                <!-- **********************************************************************************************************************************************************
                    RIGHT SIDEBAR CONTENT
                    *********************************************************************************************************************************************************** -->
            </section>
        </section>
        <!--main content end-->
        <!--footer start-->
        <footer></footer>
        <!--footer end-->
    </section>
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/Content/lib/jquery/jquery.min.js"></script>

    <script src="~/Content/lib/bootstrap/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="~/Content/lib/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/Content/lib/jquery.scrollTo.min.js"></script>
    <script src="~/Content/lib/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/Content/lib/jquery.sparkline.js"></script>
    <!--common script for all pages-->
    <script src="~/Content/lib/common-scripts.js"></script>
    <script type="text/javascript" src="~/Content/lib/gritter/js/jquery.gritter.js"></script>
    <script type="text/javascript" src="~/Content/lib/gritter-conf.js"></script>
    <!--script for this page-->
    <script src="~/Content/lib/sparkline-chart.js"></script>
    <script src="~/Content/lib/zabuto_calendar.js"></script>
   
    <script type="application/javascript">
        $(document).ready(function() {
          $("#date-popover").popover({
            html: true,
            trigger: "manual"
          });
          $("#date-popover").hide();
          $("#date-popover").click(function(e) {
            $(this).hide();
          });

          $("#my-calendar").zabuto_calendar({
            action: function() {
              return myDateFunction(this.id, false);
            },
            action_nav: function() {
              return myNavFunction(this.id);
            },
            ajax: {
              url: "show_data.php?action=1",
              modal: true
            },
            legend: [{
                type: "text",
                label: "Special event",
                badge: "00"
              },
              {
                type: "block",
                label: "Regular event",
              }
            ]
          });
        });

        function myNavFunction(id) {
          $("#date-popover").hide();
          var nav = $("#" + id).data("navigation");
          var to = $("#" + id).data("to");
          console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>
</body>

</html>